version: "3.7"
services:
  app:
    build:
      args:
        user: pie
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pastryshop
    container_name: pastryshop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pastryshop

  db:
    image: mysql:8.0
    container_name: mysql57
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql:rw
    networks:
      - pastryshop

  nginx:
    image: nginx:alpine
    container_name: pastryshop-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pastryshop

networks:
  pastryshop:
    driver: bridge
